theme: jekyll-theme-cayman
title: [Re-engaging the Body and Gesture in Musical Live Coding]
description: [This NIME 2018 workshop will re-examine notions of gesture and embodiment in musical live coding performance.]
