theme: jekyll-theme-cayman
title: [NIME 2018 Workshop: Re-engaging the Body and Gesture in Musical Live Coding]
description: [This workshop, to be held at NIME 2018 in Blacksburg, VA, USA, will re-examine notions of gesture and embodiment in musical live coding performance.]
